### ISSUE TITLE
sdc_url is hardcoded, doesn't allow for on premises use.

### ISSUE THREAD

**Issue by gileshinchcliff** [draios/python-sdc-client#1]
Hey guys.

I've found on the file _client.py the line:

   ` def __init__(self, token="", sdc_url='https://app.sysdigcloud.com'):`
is hardcoded meaning anyone using on premises sysdig would have to fork and edit manually.

Any chance to add a environment variable or flag to the command to make it more user friendly.

Thanks

Giles

**Comment by gianlucaborello** [comment]
Hey Giles,

You can actually set the environment variable `SDC_URL` (https://github.com/draios/python-sdc-client/blob/master/sdcclient/_client.py#L14) or even pass the `sdc_url` parameter when you construct the `SdcClient` object.

Let us know if that doesn't work for you.

**Comment by gileshinchcliff** [comment]
ahhh didn't see that. thanks
