### ISSUE TITLE
Suggestion: Use OpenAPI spec to define REST interface

### ISSUE THREAD

**Issue by jgensler8** [draios/python-sdc-client#20]
Hello!

I have spent a bit of time inspecting this repository and have to built an initial Swagger V2 spec. I am building an application in Go to automatically create alerts and dashboards so I have only implemented those endpoints. Because alerts and dashboards are mounted on different base paths, I have split apart the two into two specs.

Main API: https://app.swaggerhub.com/api/jgensler8/sysdig/1.0.0
Dashboard API: https://app.swaggerhub.com/api/jgensler8/sysdig-ui/1.0.0

Here are sample API clients in Go:
Main API: https://github.com/jgensler8/go-sysdig
Dashboard API: https://github.com/jgensler8/go-sysdig-ui

These generated APIs can still use wrapping code to make the interface a tad bit easier but, IMHO, this outweighs writing a whole REST interface per language.

Please let me know if this is helpful or if I should transfer ownership of the Spec I have written so far!

**Comment by philrz** [comment]
Thanks for the suggestion. We'll keep it in mind. No need to transfer ownership at this time.
