### ISSUE TITLE
using filters like contains,in , not in for alert 

### ISSUE THREAD

**Issue by amolsh** [draios/python-sdc-client#21]
Hi,

I am creating alerts using python-sdc-client. I wanted to use filters in alerts for conditions like **"contains", "in" , "does not contain", "not in", "starts with"** etc. 
**for ex. container.name 'contains' xyz.**

I am not sure how to do that. Documentation does not explain, how to use such conditions. 
Can you please help me to figure out?

res = sdclient.create_alert('APITest-KubeApi-Server down(Please Ignore)',                                                    
                            'this alert was automatically created using the python Sysdig Cloud library',
                            6,                                                                                
                            60,                                                                                 
                            'timeAvg(uptime) = 0',                                                      
                            ['host.hostName', 'container.name'],                            
                            'ANY',                           
                            'agent.tag.kubenode = "controller" and **container.name contains "xyz"**',         
                            notification_channel_ids,
                            False)

**Comment by philrz** [comment]
@amolsh,

I think I need to better understand the nature of your question. As you opened it against this Python client, I initially assumed you were having an issue with the functioning of the client. However, as I confirmed in your original issue, the code you pasted above seems to create the intended alert when I use it in the `examples/create_alert.py`. Here's how it looks in my UI:

![image](https://cloud.githubusercontent.com/assets/5934157/23965783/5ff6e902-0976-11e7-85bf-6c754dd866a7.png)

Therefore, please help me understand which we need to pursue:

1. If you're having difficulty using the Python client to create this alert, please paste an error message, the rest of the script you're using, and anything else that might help me to reproduce the issue. Or,

2. If you're just having difficulty understanding how those filters operate. The screenshot below shows the tooltip that appears for that config element.

![image](https://cloud.githubusercontent.com/assets/5934157/23965826/8bc69262-0976-11e7-8c5b-393c9a0b7fae.png)

If this is still unclear to you, it would be helpful to understand the goal of what you're trying to achieve in your alerting and how you're expecting such filters would achieve that, and we can confirm if there's a mismatch. As much as I don't like shuffling you around, if this is what needs to be discussed, it would be ideal if we pick up that topic in a Support ticket that you could open via https://support.sysdigcloud.com, as people there are better positioned to handle general product use questions, whereas this repo is focused on just the open source Python client.

**Comment by amolsh** [comment]
@philrz ,
Thanks.
Actually your comment itself solved my doubt. I am closing the issue.
