### ISSUE TITLE
send notifications to webhook

### ISSUE THREAD

**Issue by amolsh** [draios/python-sdc-client#22]
Hi,
I am using python sdc client for generating my alerts. I wanted to send alerts to "Webhook". Looks like python sdc client doesn't have capability to send alert to "webhook". Can you please add it.
for ex.
notify_channels = [ {'type': 'OPSGENIE', 'name': 'Cloud Platform OpsGenie'},
                                {'type': 'WEBHOOK', 'name': 'Cloud Alert Manager'}
                             ]

**Comment by amolsh** [comment]
@philrz 
last time you added alerts for "opsgenei" , it was very helpful. Please, can you add it for 'webhook' also. It will be great help. Thanks!

**Comment by philrz** [comment]
@amolsh,

I've merged the support for Webhook. Sorry that took several days. Are you ok with just working off the latest code in the repo? If you need a new package cut for the PyPI server so you can just `pip install` to get the version with that support, I could do that, but if possible I'd prefer to wait to do that until we've collected up more bug fixes and enhancements before we do that.

Closing this issue, but I'll watch for your reply.

**Comment by amolsh** [comment]
Thanks @philrz , I will go forward with latest code in repo till new release.
